[2025-07-02T08:42:22.682] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 10; availableParallelism: 10
[2025-07-02T08:42:22.684] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
[2025-07-02T08:42:22.689] [WARN] [localhost] [docId] [userId] nodeJS - worker 800 started.
[2025-07-02T08:42:22.690] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 10; availableParallelism: 10
[2025-07-02T08:42:22.690] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
[2025-07-02T08:42:37.322] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 10; availableParallelism: 10
[2025-07-02T08:42:37.323] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
[2025-07-02T08:42:37.325] [WARN] [localhost] [docId] [userId] nodeJS - worker 1021 started.
[2025-07-02T08:42:37.325] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 10; availableParallelism: 10
[2025-07-02T08:42:37.326] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
[2025-07-02T08:46:31.686] [ERROR] [localhost] [192.168.65.1new.docx1751445991255] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new.docx&useraddress=192.168.65.1;attempt=1;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
[2025-07-02T08:46:32.697] [ERROR] [localhost] [192.168.65.1new.docx1751445991255] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new.docx&useraddress=192.168.65.1;attempt=2;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
[2025-07-02T08:46:33.707] [ERROR] [localhost] [192.168.65.1new.docx1751445991255] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new.docx&useraddress=192.168.65.1;attempt=3;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
[2025-07-02T08:46:39.550] [ERROR] [localhost] [192.168.65.1new__1_.docx1751445999337] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new%20(1).docx&useraddress=192.168.65.1;attempt=1;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
[2025-07-02T08:46:40.561] [ERROR] [localhost] [192.168.65.1new__1_.docx1751445999337] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new%20(1).docx&useraddress=192.168.65.1;attempt=2;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
[2025-07-02T08:46:41.568] [ERROR] [localhost] [192.168.65.1new__1_.docx1751445999337] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new%20(1).docx&useraddress=192.168.65.1;attempt=3;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
[2025-07-02T08:46:55.436] [ERROR] [localhost] [192.168.65.1new__2_.docx1751446015220] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new%20(2).docx&useraddress=192.168.65.1;attempt=1;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
[2025-07-02T08:46:56.449] [ERROR] [localhost] [192.168.65.1new__2_.docx1751446015220] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new%20(2).docx&useraddress=192.168.65.1;attempt=2;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
[2025-07-02T08:46:57.461] [ERROR] [localhost] [192.168.65.1new__2_.docx1751446015220] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new%20(2).docx&useraddress=192.168.65.1;attempt=3;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
[2025-07-02T09:01:15.841] [ERROR] [localhost] [192.168.65.1new.xlsx1751446875408] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new.xlsx&useraddress=192.168.65.1;attempt=1;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
[2025-07-02T09:01:16.850] [ERROR] [localhost] [192.168.65.1new.xlsx1751446875408] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new.xlsx&useraddress=192.168.65.1;attempt=2;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
[2025-07-02T09:01:17.867] [ERROR] [localhost] [192.168.65.1new.xlsx1751446875408] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new.xlsx&useraddress=192.168.65.1;attempt=3;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
[2025-07-02T09:01:24.433] [ERROR] [localhost] [192.168.65.1new.pptx1751446884075] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new.pptx&useraddress=192.168.65.1;attempt=1;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
[2025-07-02T09:01:25.445] [ERROR] [localhost] [192.168.65.1new.pptx1751446884075] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new.pptx&useraddress=192.168.65.1;attempt=2;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
[2025-07-02T09:01:26.455] [ERROR] [localhost] [192.168.65.1new.pptx1751446884075] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new.pptx&useraddress=192.168.65.1;attempt=3;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
[2025-07-02T09:01:49.088] [ERROR] [localhost] [192.168.65.1new.docx1751446908787] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new.docx&useraddress=192.168.65.1;attempt=1;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
[2025-07-02T09:01:50.097] [ERROR] [localhost] [192.168.65.1new.docx1751446908787] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new.docx&useraddress=192.168.65.1;attempt=2;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
[2025-07-02T09:01:51.108] [ERROR] [localhost] [192.168.65.1new.docx1751446908787] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new.docx&useraddress=192.168.65.1;attempt=3;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
    at Function.from (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.handleRequestError (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at RedirectableRequest.emit (node:events:536:35)
    at ClientRequest.<anonymous> (/snapshot/server/Common/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:524:28)
    at emitErrorEvent (node:_http_client:101:11)
    at Socket.socketErrorListener (node:_http_client:504:5)
    at Socket.emit (node:events:524:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at Axios.request (/snapshot/server/Common/node_modules/axios/dist/node/axios.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.downloadUrlPromise (/snapshot/server/Common/sources/utils.js)
